version: '3'
services:
  nginx:
    image: flashspys/nginx-static
    container_name: web_ar
    restart: unless-stopped
    volumes:
      - ./html:/static
    networks:
      - proxy
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.web_ar.entrypoints=websecure"
      - "traefik.http.routers.web_ar.rule=Host(`planthelper.ru`)"
      - "traefik.http.services.web_ar.loadbalancer.server.port=80"
networks:
  proxy:
    external: true
